/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class ThuTien extends javax.swing.JPanel {

    /**
     * Creates new form ThuTien
     */
    public ThuTien() {
        initComponents();
         // Lấy component JTextField của JDateChooser
        JTextField dateTextField = (JTextField) jDateChooser1.getDateEditor().getUiComponent();

        // Thiết lập màu nền cho JTextField
        dateTextField.setBackground(new java.awt.Color(98, 204, 254));
        JTextField dateField = (JTextField) jDateChooser1.getDateEditor().getUiComponent();
        // Đặt placeholder
        String placeholder = "Ngày thu tiền";
        dateField.setText(placeholder);
        dateField.setForeground(new java.awt.Color(0,49,64));
        // Thêm sự kiện Focus để xử lý khi focus vào hoặc ra khỏi trường nhập liệu
        dateField.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (dateField.getText().equals(placeholder)) {
                dateField.setText("");
                dateField.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (dateField.getText().isEmpty()) {
                dateField.setText(placeholder);
                dateField.setForeground(Color.GRAY);
            }
        }
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.component.Background();
        panelBorder1 = new com.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        hoTen = new javax.swing.JTextField();
        dienThoai = new javax.swing.JTextField();
        diaChi = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        soTienThu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        panelBorder1.setBackground(new java.awt.Color(0, 88, 128));

        jLabel1.setBackground(new java.awt.Color(0, 88, 128));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU THU TIỀN");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDateChooser1.setBackground(new java.awt.Color(98, 204, 254));
        jDateChooser1.setForeground(new java.awt.Color(0, 49, 64));

        hoTen.setBackground(new java.awt.Color(138, 218, 254));
        hoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hoTen.setForeground(new java.awt.Color(0, 49, 64));
        hoTen.setText("Họ và tên");
        hoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 49, 64)));
        hoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hoTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hoTenFocusLost(evt);
            }
        });

        dienThoai.setBackground(new java.awt.Color(98, 204, 254));
        dienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dienThoai.setForeground(new java.awt.Color(0, 49, 64));
        dienThoai.setText("Điện thoại");
        dienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 49, 64)));
        dienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dienThoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dienThoaiFocusLost(evt);
            }
        });

        diaChi.setBackground(new java.awt.Color(138, 218, 254));
        diaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diaChi.setForeground(new java.awt.Color(0, 49, 64));
        diaChi.setText("Địa chỉ");
        diaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 49, 64)));
        diaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diaChiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaChiFocusLost(evt);
            }
        });

        email.setBackground(new java.awt.Color(98, 204, 254));
        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 49, 64));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 49, 64)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        soTienThu.setBackground(new java.awt.Color(98, 204, 254));
        soTienThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soTienThu.setForeground(new java.awt.Color(0, 49, 64));
        soTienThu.setText("Số tiền thu");
        soTienThu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 49, 64)));
        soTienThu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                soTienThuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                soTienThuFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 88, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("XÁC NHẬN");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(129, 129, 129))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(soTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(dienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(soTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hoTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hoTenFocusGained
        if("Họ và tên".equals(hoTen.getText())){
            hoTen.setText("");
        }
    }//GEN-LAST:event_hoTenFocusGained

    private void hoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hoTenFocusLost
        if("".equals(hoTen.getText())){
            hoTen.setText("Họ và tên");
        }
    }//GEN-LAST:event_hoTenFocusLost

    private void dienThoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dienThoaiFocusGained
        // TODO add your handling code here:
        if("Điện thoại".equals(dienThoai.getText())){
            dienThoai.setText("");
        }
    }//GEN-LAST:event_dienThoaiFocusGained

    private void dienThoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dienThoaiFocusLost
        // TODO add your handling code here:
        if("".equals(dienThoai.getText())){
            dienThoai.setText("Điện thoại");
        }
    }//GEN-LAST:event_dienThoaiFocusLost

    private void diaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaChiFocusGained
        // TODO add your handling code here:
        if("Địa chỉ".equals(diaChi.getText())){
            diaChi.setText("");
        }
    }//GEN-LAST:event_diaChiFocusGained

    private void diaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaChiFocusLost
        // TODO add your handling code here:
        if("".equals(dienThoai.getText())){
            dienThoai.setText("Địa chỉ");
        }
    }//GEN-LAST:event_diaChiFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if("Email".equals(email.getText())){
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if("".equals(dienThoai.getText())){
            dienThoai.setText("Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void soTienThuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_soTienThuFocusGained
        // TODO add your handling code here:
        if("Số tiền thu".equals(soTienThu.getText())){
            soTienThu.setText("");
        }
    }//GEN-LAST:event_soTienThuFocusGained

    private void soTienThuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_soTienThuFocusLost
        // TODO add your handling code here:
        if("".equals(dienThoai.getText())){
            dienThoai.setText("Số tiền thu");
        }
    }//GEN-LAST:event_soTienThuFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.component.Background background1;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField dienThoai;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hoTen;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private com.swing.PanelBorder panelBorder1;
    private javax.swing.JTextField soTienThu;
    // End of variables declaration//GEN-END:variables
}
