/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static UI.DatabaseConnect.getJDBCConnection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

class CTNhap {

    private String maSach;
    private String tenSach;
    private int soLuong;
    private double gia;
    private String tacgia;
    private String theloai;
    
    public CTNhap(String maSach, String tenSach, int soLuong, double gia, String tacgia, String theloai) {
        this.maSach = maSach;
        this.tenSach = tenSach;
        this.soLuong = soLuong;
        this.gia = gia;
        this.tacgia = tacgia;
        this.theloai = theloai;
    }

    public String getMaSach() {
        return maSach;
    }

    public String getTenSach() {
        return tenSach;
    }

    public int getSoLuong() {
        return soLuong;
    }

    public double getGia() {
        return gia;
    }

    public String getTacgia() {
        return tacgia;
    }

    public String getTheloai() {
        return theloai;
    }
    
    
}
public class NhapSach extends javax.swing.JPanel {
    Connection conn = getJDBCConnection();
    PreparedStatement ps = null;
    ResultSet rs = null;
    List<CTNhap> danhSachPhieuNhap = new ArrayList<>();
    public NhapSach() {
        initComponents();
        setTable1Header();
        loadComboBox();
    }
    private void loadTable1(){
        // create jTable1 columns
        DefaultTableModel model = new DefaultTableModel(){
            //không cho chỉnh sửa trong bảng
            @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        String tieude[] = new String[]{ "STT", "Mã sách", "Tên sách", "Tác giả" , "Thể loại" ,"Số lượng", "Đơn giá nhập"};
        model.setColumnIdentifiers(tieude); 
        for(int i = 0 ;i<danhSachPhieuNhap.size();i++)
            model.addRow(new Object[]{(i+1), danhSachPhieuNhap.get(i).getMaSach(),danhSachPhieuNhap.get(i).getTenSach(),danhSachPhieuNhap.get(i).getTacgia(),danhSachPhieuNhap.get(i).getTheloai(),danhSachPhieuNhap.get(i).getSoLuong(),danhSachPhieuNhap.get(i).getGia()});
        tb_phieunhap.setModel(model);
    }
    private void loadComboBox(){
        MS.removeAllItems();
        String sql = "SELECT * FROM SACH";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            MS.addItem("Chọn mã sách");
            while(rs.next()){
                MS.addItem(rs.getString("MASACH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setTable1Header(){
        tb_phieunhap.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            l.setBackground(new Color(0,88,128));
            l.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
            l.setHorizontalAlignment(CENTER);
            l.setFont(new Font("Segoe UI",Font.BOLD, 16));            
            return l;
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.component.Background();
        title_PN = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TSF = new javax.swing.JLabel();
        lb_tensach = new javax.swing.JLabel();
        lb_tacgia = new javax.swing.JLabel();
        l_nxb = new javax.swing.JLabel();
        lb_soluong = new javax.swing.JLabel();
        SL = new javax.swing.JTextField();
        ThemSach = new javax.swing.JButton();
        TS = new javax.swing.JTextField();
        TG = new javax.swing.JTextField();
        NamXB = new javax.swing.JTextField();
        NXB = new javax.swing.JTextField();
        lb_theloai1 = new javax.swing.JLabel();
        DGN = new javax.swing.JTextField();
        XoaSach = new javax.swing.JButton();
        lb_tacgia1 = new javax.swing.JLabel();
        MS = new javax.swing.JComboBox<>();
        TraCuuPN = new javax.swing.JButton();
        Finish = new javax.swing.JButton();
        NN = new javax.swing.JTextField();
        lb_ngaynhap = new javax.swing.JLabel();
        tablePanel = new com.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_phieunhap = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(838, 651));

        background1.setPreferredSize(new java.awt.Dimension(838, 651));

        title_PN.setBackground(new java.awt.Color(0, 0, 153));
        title_PN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        title_PN.setForeground(new java.awt.Color(0, 0, 102));
        title_PN.setText("PHIẾU NHẬP SÁCH");
        title_PN.setInheritsPopupMenu(false);

        jPanel1.setBackground(background1.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 88, 128), 2));
        jPanel1.setOpaque(false);

        TSF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TSF.setText("Tên sách");

        lb_tensach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tensach.setText("Năm xuất bản");

        lb_tacgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tacgia.setText("Tác giả");

        l_nxb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_nxb.setText("Nhà xuất bản");

        lb_soluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_soluong.setText("Số lượng");

        ThemSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ThemSach.setText("Thêm");
        ThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemSachActionPerformed(evt);
            }
        });

        TS.setEnabled(false);

        TG.setEnabled(false);

        NamXB.setEnabled(false);

        NXB.setEnabled(false);

        lb_theloai1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_theloai1.setText("Đơn giá nhập");

        XoaSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        XoaSach.setText("Xóa");
        XoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaSachActionPerformed(evt);
            }
        });

        lb_tacgia1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tacgia1.setText("Mã sách");

        MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_theloai1)
                    .addComponent(lb_tacgia)
                    .addComponent(lb_tensach)
                    .addComponent(lb_tacgia1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NamXB, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(TG)
                    .addComponent(DGN)
                    .addComponent(MS, 0, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_soluong)
                            .addComponent(l_nxb)
                            .addComponent(TSF))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(NXB)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(XoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSF)
                    .addComponent(TS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tacgia1)
                    .addComponent(MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nxb)
                    .addComponent(NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tacgia)
                    .addComponent(TG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soluong)
                    .addComponent(SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tensach)
                    .addComponent(NamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_theloai1)
                        .addComponent(DGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TSF.getAccessibleContext().setAccessibleName("");
        lb_tensach.getAccessibleContext().setAccessibleName("");
        l_nxb.getAccessibleContext().setAccessibleName("");
        lb_soluong.getAccessibleContext().setAccessibleName("");
        SL.getAccessibleContext().setAccessibleName("tx_soluong");
        ThemSach.getAccessibleContext().setAccessibleName("bt_them");

        TraCuuPN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TraCuuPN.setText("Tra cứu phiếu nhập");
        TraCuuPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraCuuPNMouseClicked(evt);
            }
        });
        TraCuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraCuuPNActionPerformed(evt);
            }
        });

        Finish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Finish.setText("Hoàn tất");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        lb_ngaynhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ngaynhap.setText("Ngày nhập (dd/MM/yyyy)");

        tablePanel.setBackground(new java.awt.Color(0, 88, 128));

        jScrollPane1.setBorder(null);

        tb_phieunhap.setBackground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setForeground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả ", "Thể loại", "Số lượng", "Đơn giá nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_phieunhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_phieunhap.setFillsViewportHeight(true);
        tb_phieunhap.setGridColor(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setRowHeight(40);
        tb_phieunhap.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setSelectionForeground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tb_phieunhap);
        tb_phieunhap.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lb_ngaynhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NN, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(background1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(background1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(title_PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TraCuuPN, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ngaynhap)
                    .addComponent(Finish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(background1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(title_PN)
                    .addGap(18, 18, 18)
                    .addComponent(TraCuuPN)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        TraCuuPN.getAccessibleContext().setAccessibleName("bt_tracuu");
        Finish.getAccessibleContext().setAccessibleName("bt_xacnhan");
        NN.getAccessibleContext().setAccessibleName("tx_ngaynhap");
        lb_ngaynhap.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private int getSLTon(String masach){
        String sql = "SELECT SLTON FROM SACH WHERE MASACH = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, masach);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SLTon");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private void TraCuuPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraCuuPNMouseClicked
        
    }//GEN-LAST:event_TraCuuPNMouseClicked
    private int getSLNTT(){
        String sql = "SELECT SOLUONGNHAPTOITHIEU FROM THAMSO";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SOLUONGNHAPTOITHIEU");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private int getSLTTDTN(){
        String sql = "SELECT SOLUONGTONTOIDATRUOCNHAP FROM THAMSO";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SOLUONGTONTOIDATRUOCNHAP");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private void addToCTPN(String masach, String tensach, String sl, String dgn, String tacgia, String theloai){
        int soluong = Integer.parseInt(sl);
        float dongianhap = Float.parseFloat(dgn);
        danhSachPhieuNhap.add(new CTNhap(masach, tensach, soluong, dongianhap, tacgia, theloai));
        TS.setText("");
        TG.setText("");
        NamXB.setText("");
        NXB.setText("");
        SL.setText("");
        DGN.setText("");
        MS.setSelectedIndex(0);
        loadTable1();
    }
    private void ThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemSachActionPerformed
        String ts = TS.getText();
        String tg = TG.getText();
        String sl = SL.getText();
        String dgn = DGN.getText();
        String maSach = MS.getSelectedItem().toString();
        if("Chọn mã khách hàng".equals(maSach)||sl.isBlank()||dgn.isBlank()){
            JOptionPane.showMessageDialog(NhapSach.this, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        int slntt = getSLNTT(); //số lượng nhập tối thiểu
        System.out.println("SLNTT: "+slntt);
        if(Integer.parseInt(sl)<slntt){
            JOptionPane.showMessageDialog(NhapSach.this, "Số lượng nhập phải lớn hơn số lượng nhập tối thiểu");
            return;
        }
        String tl = "";
        int slttdtn = getSLTTDTN(); //số lượng tồn tối đa trước nhập
        System.out.println("SLTTDTN: "+slttdtn);
        int slton = getSLTon(maSach);
        if(slton > slttdtn){
            JOptionPane.showMessageDialog(NhapSach.this, "Số lượng tồn phải nhỏ hơn số lượng tồn tối đa trước nhập");
            return;
        }
        addToCTPN(maSach,ts,sl,dgn,tg,tl);
    }//GEN-LAST:event_ThemSachActionPerformed

    private void XoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaSachActionPerformed
        int rowNo = tb_phieunhap.getSelectedRow();
        if(rowNo>-1){
            danhSachPhieuNhap.remove(rowNo);
            loadTable1();
        }
    }//GEN-LAST:event_XoaSachActionPerformed
    private String createPNS(){
        String sql = "INSERT INTO phieunhapsach (TONGSLNHAP, TONGTIEN, NGAYNHAP) VALUES (?,?,?)";
        String ngay = NN.getText(); //dd/MM/yyyy
        DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = LocalDate.parse(ngay, inputFormatter);
        String formattedNgay = date.format(outputFormatter);
        Date nn = Date.valueOf(formattedNgay);
        Double tongtien = 0.0;
        int tongsl = 0;
        for(CTNhap sach : danhSachPhieuNhap){
            tongsl += sach.getSoLuong();
            tongtien += sach.getGia()*sach.getSoLuong();
        }
        try {
            ps = conn.prepareStatement(sql);
            ps.setInt(1, tongsl);
            ps.setDouble(2, tongtien);
            ps.setDate(3, nn);
            ps.executeUpdate();
            ps.close();
            sql = "select last_insert_id()";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            String mpn = null;
            if(rs.next()){
                mpn = rs.getString(1);
                JOptionPane.showMessageDialog(NhapSach.this, "Thêm phiếu nhập sách thành công");
            }
            return mpn;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    private void updateCTNS(String mpn){
        String sql = "INSERT INTO chitietnhapsach (MAPHIEUNHAP, MASACH, GIANHAP, SLNHAP) VALUES (?,?,?,?)";
        try {
            ps = conn.prepareStatement(sql);
            for(CTNhap sach : danhSachPhieuNhap){
                ps.setString(1, mpn);
                ps.setString(2, sach.getMaSach());
                ps.setDouble(3, sach.getGia());
                ps.setInt(4, sach.getSoLuong());
                ps.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void updateSach(){
        String sql = "UPDATE sach SET SLTON = SLTON+? , DONGIANHAP= ? WHERE MASACH = ?";
        try {
            ps = conn.prepareStatement(sql);
            for(CTNhap sach : danhSachPhieuNhap){
                ps.setInt(1, sach.getSoLuong());
                ps.setDouble(2, sach.getGia());
                ps.setString(3, sach.getMaSach());
                // không cần cập nhật đơn giá bán vì khi bán sách sẽ lấy giá nhập * tỉ lệ sau
                ps.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        if(!danhSachPhieuNhap.isEmpty()&&!NN.getText().isBlank()){
            String mpn = createPNS();
            updateCTNS(mpn);
            updateSach();
            NN.setText("");
            danhSachPhieuNhap.clear();
            loadTable1();
        }
        else{
            JOptionPane.showMessageDialog(NhapSach.this, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_FinishActionPerformed

    private void TraCuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraCuuPNActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        TracuuPhieunhap tracuu = new TracuuPhieunhap();
        frame.add(tracuu);
        frame.setSize(838, 651);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_TraCuuPNActionPerformed

    private void MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSActionPerformed
        if("Chọn mã sách".equals(MS.getSelectedItem().toString())){
            TS.setText("");
            NamXB.setText("");
            NXB.setText("");
            TG.setText("");
            return;
        }
        String sql = "SELECT * FROM SACH JOIN DAUSACH ON DAUSACH.MADAUSACH = SACH.MADAUSACH JOIN cttacgia ON CTTACGIA.MADAUSACH = DAUSACH.MADAUSACH JOIN TACGIA ON CTTACGIA.MATG = TACGIA.MATG WHERE MASACH = ?";
        String masach = MS.getSelectedItem().toString();
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, masach);
            rs = ps.executeQuery();
            while(rs.next()){
                TS.setText(rs.getString("TENDAUSACH"));
                NamXB.setText(rs.getString("NAMXB"));
                NXB.setText(rs.getString("NXB"));
                TG.setText(rs.getString("TENTG"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThuTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DGN;
    private javax.swing.JButton Finish;
    private javax.swing.JComboBox<String> MS;
    private javax.swing.JTextField NN;
    private javax.swing.JTextField NXB;
    private javax.swing.JTextField NamXB;
    private javax.swing.JTextField SL;
    private javax.swing.JTextField TG;
    private javax.swing.JTextField TS;
    private javax.swing.JLabel TSF;
    private javax.swing.JButton ThemSach;
    private javax.swing.JButton TraCuuPN;
    private javax.swing.JButton XoaSach;
    private com.component.Background background1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_nxb;
    private javax.swing.JLabel lb_ngaynhap;
    private javax.swing.JLabel lb_soluong;
    private javax.swing.JLabel lb_tacgia;
    private javax.swing.JLabel lb_tacgia1;
    private javax.swing.JLabel lb_tensach;
    private javax.swing.JLabel lb_theloai1;
    private com.swing.PanelBorder tablePanel;
    private javax.swing.JTable tb_phieunhap;
    private javax.swing.JLabel title_PN;
    // End of variables declaration//GEN-END:variables
}
