/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static UI.DatabaseConnect.getJDBCConnection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

class CTNhap {

    private String maSach;
    private String tenSach;
    private int soLuong;
    private double gia;
    private String tacgia;
    private String theloai;
    
    public CTNhap(String maSach, String tenSach, int soLuong, double gia, String tacgia, String theloai) {
        this.maSach = maSach;
        this.tenSach = tenSach;
        this.soLuong = soLuong;
        this.gia = gia;
        this.tacgia = tacgia;
        this.theloai = theloai;
    }

    public String getMaSach() {
        return maSach;
    }

    public String getTenSach() {
        return tenSach;
    }

    public int getSoLuong() {
        return soLuong;
    }

    public double getGia() {
        return gia;
    }

    public String getTacgia() {
        return tacgia;
    }

    public String getTheloai() {
        return theloai;
    }
    
    
}
public class NhapSach extends javax.swing.JPanel {
    Connection conn = getJDBCConnection();
    PreparedStatement ps = null;
    ResultSet rs = null;
    List<CTNhap> danhSachPhieuNhap = new ArrayList<>();
    public NhapSach() {
        initComponents();
        setTable1Header();
    }
    private void loadTable1(){
        // create jTable1 columns
        DefaultTableModel model = new DefaultTableModel(){
            //không cho chỉnh sửa trong bảng
            @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        String mapn = MPN.getText();
        String tieude[] = new String[]{ "STT", "Mã sách", "Tên sách", "Tác giả" , "Thể loại" ,"Số lượng", "Đơn giá nhập"};
        model.setColumnIdentifiers(tieude);
        if(mapn.isBlank()){
           model.setRowCount(0);
           tb_phieunhap.setModel(model);
           return;
        }   
        for(int i = 0 ;i<danhSachPhieuNhap.size();i++)
            model.addRow(new Object[]{(i+1), danhSachPhieuNhap.get(i).getMaSach(),danhSachPhieuNhap.get(i).getTenSach(),danhSachPhieuNhap.get(i).getTacgia(),danhSachPhieuNhap.get(i).getTheloai(),danhSachPhieuNhap.get(i).getSoLuong(),danhSachPhieuNhap.get(i).getGia()});
        tb_phieunhap.setModel(model);
    }
    private void setTable1Header(){
        tb_phieunhap.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            l.setBackground(new Color(0,88,128));
            l.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
            l.setHorizontalAlignment(CENTER);
            l.setFont(new Font("Segoe UI",Font.BOLD, 16));            
            return l;
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String getLastestMaPN(){
        String sql = "SELECT * FROM PHIEUNHAPSACH";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            int rowCount = 0;
            while (rs.next()) {
                rowCount++;
            }
            String mpn = "MPN"+rowCount;
            return mpn;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return "";
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.component.Background();
        title_PN = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TSF = new javax.swing.JLabel();
        lb_tensach = new javax.swing.JLabel();
        lb_theloai = new javax.swing.JLabel();
        lb_tacgia = new javax.swing.JLabel();
        l_nxb = new javax.swing.JLabel();
        lb_soluong = new javax.swing.JLabel();
        SL = new javax.swing.JTextField();
        ThemSach = new javax.swing.JButton();
        TS = new javax.swing.JTextField();
        TG = new javax.swing.JTextField();
        NamXB = new javax.swing.JTextField();
        NXB = new javax.swing.JTextField();
        TL = new javax.swing.JTextField();
        lb_theloai1 = new javax.swing.JLabel();
        DGN = new javax.swing.JTextField();
        XoaSach = new javax.swing.JButton();
        TraCuuPN = new javax.swing.JButton();
        Finish = new javax.swing.JButton();
        MPN = new javax.swing.JTextField();
        lb_maphieu = new javax.swing.JLabel();
        NN = new javax.swing.JTextField();
        lb_ngaynhap = new javax.swing.JLabel();
        tablePanel = new com.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_phieunhap = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(838, 651));

        background1.setPreferredSize(new java.awt.Dimension(838, 651));

        title_PN.setBackground(new java.awt.Color(0, 0, 153));
        title_PN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        title_PN.setForeground(new java.awt.Color(0, 0, 102));
        title_PN.setText("PHIẾU NHẬP SÁCH");
        title_PN.setInheritsPopupMenu(false);

        jPanel1.setBackground(background1.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 88, 128), 2));
        jPanel1.setOpaque(false);

        TSF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TSF.setText("Tên sách");

        lb_tensach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tensach.setText("Năm xuất bản");

        lb_theloai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_theloai.setText("Thể loại");

        lb_tacgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tacgia.setText("Tác giả");

        l_nxb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_nxb.setText("Nhà xuất bản");

        lb_soluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_soluong.setText("Số lượng");

        ThemSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ThemSach.setText("Thêm");
        ThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemSachActionPerformed(evt);
            }
        });

        lb_theloai1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_theloai1.setText("Đơn giá nhập");

        XoaSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        XoaSach.setText("Xóa");
        XoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TSF)
                            .addGap(57, 57, 57))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_tensach)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_theloai)
                            .addComponent(lb_theloai1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TS, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(NamXB)
                    .addComponent(TL)
                    .addComponent(DGN))
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_soluong)
                            .addComponent(lb_tacgia)
                            .addComponent(l_nxb))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(TG)
                            .addComponent(NXB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(XoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TSF)
                            .addComponent(TS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_tacgia)
                            .addComponent(TG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tensach)
                    .addComponent(l_nxb)
                    .addComponent(NamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soluong)
                    .addComponent(lb_theloai)
                    .addComponent(SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_theloai1)
                        .addComponent(DGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TSF.getAccessibleContext().setAccessibleName("");
        lb_tensach.getAccessibleContext().setAccessibleName("");
        lb_theloai.getAccessibleContext().setAccessibleName("");
        l_nxb.getAccessibleContext().setAccessibleName("");
        lb_soluong.getAccessibleContext().setAccessibleName("");
        SL.getAccessibleContext().setAccessibleName("tx_soluong");
        ThemSach.getAccessibleContext().setAccessibleName("bt_them");

        TraCuuPN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TraCuuPN.setText("Tra cứu phiếu nhập");
        TraCuuPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraCuuPNMouseClicked(evt);
            }
        });
        TraCuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraCuuPNActionPerformed(evt);
            }
        });

        Finish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Finish.setText("Hoàn tất");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        MPN.setEditable(false);
        MPN.setFocusable(false);

        lb_maphieu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lb_maphieu.setText("Mã phiếu");

        NN.setEditable(false);
        NN.setFocusable(false);

        lb_ngaynhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ngaynhap.setText("Ngày nhập");

        tablePanel.setBackground(new java.awt.Color(0, 88, 128));

        jScrollPane1.setBorder(null);

        tb_phieunhap.setBackground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setForeground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả ", "Thể loại", "Số lượng", "Đơn giá nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_phieunhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_phieunhap.setFillsViewportHeight(true);
        tb_phieunhap.setGridColor(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setRowHeight(40);
        tb_phieunhap.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setSelectionForeground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tb_phieunhap);
        tb_phieunhap.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(background1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lb_maphieu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MPN, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_ngaynhap)
                            .addGap(18, 18, 18)
                            .addComponent(NN, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88))
                        .addGroup(background1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(title_PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TraCuuPN, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(background1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(title_PN)
                    .addGap(18, 18, 18)
                    .addComponent(TraCuuPN)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_maphieu)
                        .addComponent(NN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_ngaynhap)
                        .addComponent(Finish))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        TraCuuPN.getAccessibleContext().setAccessibleName("bt_tracuu");
        Finish.getAccessibleContext().setAccessibleName("bt_xacnhan");
        lb_maphieu.getAccessibleContext().setAccessibleName("");
        NN.getAccessibleContext().setAccessibleName("tx_ngaynhap");
        lb_ngaynhap.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private String getMaTheLoai(String theloai){
        String sql = "SELECT MATHELOAI FROM THELOAI WHERE TENTHELOAI = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, theloai);
            rs = ps.executeQuery();
            if(rs.next())
            return rs.getString("MATHELOAI");
            // không tìm thấy tên thể loại thì tạo mới
        sql = "SELECT * FROM THELOAI";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        int rowCount = 0;
            while (rs.next()) {
                rowCount++;
        }
        String matheloai = "TL"+rowCount;
        sql = "INSERT INTO THELOAI (MATHELOAI,TENTHELOAI) VALUES (?,?)";
        ps = conn.prepareStatement(sql);
        ps.setString(1, matheloai);
        ps.setString(2, theloai);
        ps.executeUpdate();
        return matheloai;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return "";
    }
    private String getMaTacGia(String tentacgia){
        String sql = "SELECT MATG FROM TACGIA WHERE TENTG = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, tentacgia);
            rs = ps.executeQuery();
            if(rs.next())
            return rs.getString("MATG");
            // không tìm thấy tên tác giả thì tạo mới
        sql = "SELECT * FROM TACGIA";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        int rowCount = 0;
            while (rs.next()) {
                rowCount++;
            }
        String matacgia = "TG"+rowCount;
        sql = "INSERT INTO TACGIA (MATG,TENTG) VALUES (?,?)";
        ps = conn.prepareStatement(sql);
        ps.setString(1, matacgia);
        ps.setString(2, tentacgia);
        ps.executeUpdate();
        return matacgia;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return "";
    }
    private String getMaDauSach(String tensach, String matheloai){
        String sql = "SELECT MADAUSACH FROM DAUSACH WHERE TENDAUSACH =? AND MATHELOAI = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, tensach);
            ps.setString(2, matheloai);
            rs = ps.executeQuery();
            if(rs.next())
            return rs.getString("MADAUSACH");
            // không tìm thấy tên đầu sách thì tạo mới
        
        sql = "SELECT * FROM DAUSACH";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        int rowCount = 0;
            while (rs.next()) {
                rowCount++;
            }
        String madausach = "DS"+rowCount;
        sql = "INSERT INTO DAUSACH (MADAUSACH, TENDAUSACH, MATHELOAI) VALUES (?,?,?)";
        ps = conn.prepareStatement(sql);
        ps.setString(1, madausach);
        ps.setString(2, tensach);
        ps.setString(3, matheloai);
        ps.executeUpdate();
        return madausach;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return "";
    }
    private int getCTTG(String madausach, String matacgia){
        String sql = "SELECT * FROM CTTACGIA WHERE MADAUSACH =? AND MATG = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, madausach);
            ps.setString(2, matacgia);
            rs = ps.executeQuery();
            if(rs.next())
            return 1;
            // không tìm thấy đầu sách - tác giả thì tạo mới
        sql = "INSERT INTO CTTACGIA (MATG, MADAUSACH) VALUES (?,?)";
        ps = conn.prepareStatement(sql);
        ps.setString(1, matacgia);
        ps.setString(2, madausach);
        ps.executeUpdate();
        return 1;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return 0;
    }
    private String getMaSach(String madausach, String namxb, String nxb, String tentacgia){
        String sql = "SELECT MASACH FROM SACH WHERE MADAUSACH =? AND NAMXB = ? AND NXB = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, madausach);
            ps.setString(2, namxb);
            ps.setString(3, nxb);
            rs = ps.executeQuery();
            if(rs.next())
            return rs.getString("MASACH");
            // không tìm thấy mã sách thì tạo mới
        
        sql = "SELECT * FROM SACH";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        int rowCount = 0;
            while (rs.next()) {
                rowCount++;
            }
        String maSach = "S"+rowCount;
        //thêm sách vào SACH
        sql = "INSERT INTO SACH (MASACH,MADAUSACH,NAMXB,NXB,SLTON) VALUES (?,?,?,?,0)";
        ps = conn.prepareStatement(sql);
        ps.setString(1, maSach);
        ps.setString(2, madausach);
        ps.setString(3, namxb);
        ps.setString(4, nxb);
        ps.executeUpdate();
        // kiểm tra xem đã tồn tại tác giả chưa /// đã xét trường hợp nhiều tác giả!!!
        String[] array = tentacgia.split(",");
        for (String item : array) {
            String matacgia = getMaTacGia(item);
            int ds_tt = getCTTG(madausach,matacgia);
        }        
        return maSach;
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(NhapSach.this, "Thông tin không hợp lệ");
        }        
        return "";
    }
    private int getSLTon(String masach){
        String sql = "SELECT SLTON FROM SACH WHERE MASACH = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, masach);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SLTon");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private void TraCuuPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraCuuPNMouseClicked
        
    }//GEN-LAST:event_TraCuuPNMouseClicked
    private int getSLNTT(){
        String sql = "SELECT SOLUONGNHAPTOITHIEU FROM THAMSO";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SOLUONGNHAPTOITHIEU");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private int getSLTTDTN(){
        String sql = "SELECT SOLUONGTONTOIDATRUOCNHAP FROM THAMSO";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next())
            return rs.getInt("SOLUONGTONTOIDATRUOCNHAP");
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return -1;
    }
    private void addToCTPN(String mpn, String masach, String sl, String dgn, String tacgia, String theloai){
        int soluong = Integer.parseInt(sl);
        float dongianhap = Float.parseFloat(dgn);
        danhSachPhieuNhap.add(new CTNhap(mpn, masach, soluong, dongianhap, tacgia, theloai));
        TS.setText("");
        TG.setText("");
        NamXB.setText("");
        NXB.setText("");
        TL.setText("");
        SL.setText("");
        DGN.setText("");
        loadTable1();
    }
    private void ThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemSachActionPerformed
        String ts = TS.getText();
        String tg = TG.getText();
        String namxb = NamXB.getText();
        String nxb = NXB.getText();
        String tl = TL.getText();
        String sl = SL.getText();
        String dgn = DGN.getText();
        if(ts.isBlank()||tg.isBlank()||namxb.isBlank()||nxb.isBlank()||tl.isBlank()||sl.isBlank()||dgn.isBlank()){
            JOptionPane.showMessageDialog(NhapSach.this, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        int slntt = getSLNTT();
        System.out.println("SLNTT: "+slntt);
        if(Integer.parseInt(sl)<slntt){
            JOptionPane.showMessageDialog(NhapSach.this, "Số lượng nhập phải lớn hơn số lượng nhập tối thiểu");
            return;
        }
        String matheloai = getMaTheLoai(tl);
        System.out.println("Ma The Loai: "+matheloai);
        String madausach = getMaDauSach(ts,matheloai);
        System.out.println("Ma Dau Sach: "+madausach);
        String masach = getMaSach(madausach,namxb,nxb,tg);
        System.out.println("Ma Sach: "+masach);
        int slttdtn = getSLTTDTN();
        System.out.println("SLTTDTN: "+slttdtn);
        int slton = getSLTon(masach);
        if(slton > slttdtn){
            JOptionPane.showMessageDialog(NhapSach.this, "Số lượng tồn phải nhỏ hơn số lượng tồn tối đa trước nhập");
            return;
        }
        String mpn = MPN.getText();
        if(mpn.isBlank()){
            mpn = getLastestMaPN();
            MPN.setText(mpn);
        }
        if(NN.getText().isBlank()){
            LocalDate today = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            NN.setText(today.format(formatter));
        }
        addToCTPN(masach,ts,sl,dgn,tg,tl);
    }//GEN-LAST:event_ThemSachActionPerformed

    private void XoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaSachActionPerformed
        int rowNo = tb_phieunhap.getSelectedRow();
        if(rowNo>-1){
            danhSachPhieuNhap.remove(rowNo);
            loadTable1();
        }
    }//GEN-LAST:event_XoaSachActionPerformed
    private void createPNS(){
        String sql = "INSERT INTO phieunhapsach (MAPHIEUNHAP,TONGSLNHAP, TONGTIEN, NGAYNHAP) VALUES (?,?,?,?)";
        String mpn = MPN.getText();
        LocalDate today = LocalDate.now();
        Date nn = Date.valueOf(today);
        Double tongtien = 0.0;
        int tongsl = 0;
        for(CTNhap sach : danhSachPhieuNhap){
            tongsl += sach.getSoLuong();
            tongtien += sach.getGia()*sach.getSoLuong();
        }
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, mpn);
            ps.setInt(2, tongsl);
            ps.setDouble(3, tongtien);
            ps.setDate(4, nn);
            int result = ps.executeUpdate();
            if(result == 1){
                JOptionPane.showMessageDialog(NhapSach.this, "Thêm phiếu nhập sách thành công");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void updateCTNS(){
        String sql = "INSERT INTO chitietnhapsach (MAPHIEUNHAP, MASACH, GIANHAP, SLNHAP) VALUES (?,?,?,?)";
        String mpn = MPN.getText();
        try {
            ps = conn.prepareStatement(sql);
            for(CTNhap sach : danhSachPhieuNhap){
                ps.setString(1, mpn);
                ps.setString(2, sach.getMaSach());
                ps.setDouble(3, sach.getGia());
                ps.setInt(4, sach.getSoLuong());
                ps.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void updateSach(){
        String sql = "UPDATE sach SET SLTON = SLTON+? , DONGIANHAP= ? WHERE MASACH = ?";
        try {
            ps = conn.prepareStatement(sql);
            for(CTNhap sach : danhSachPhieuNhap){
                ps.setInt(1, sach.getSoLuong());
                ps.setDouble(2, sach.getGia());
                ps.setString(3, sach.getMaSach());
                // không cần cập nhật đơn giá bán vì khi bán sách sẽ lấy giá nhập * tỉ lệ sau
                ps.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        if(!danhSachPhieuNhap.isEmpty()&&!MPN.getText().isBlank()){
            createPNS();
            updateCTNS();
            updateSach();
            MPN.setText("");
            NN.setText("");
            danhSachPhieuNhap.clear();
            loadTable1();
        }
    }//GEN-LAST:event_FinishActionPerformed

    private void TraCuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraCuuPNActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        TracuuPhieunhap tracuu = new TracuuPhieunhap();
        frame.add(tracuu);
        frame.setSize(838, 651);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_TraCuuPNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DGN;
    private javax.swing.JButton Finish;
    private javax.swing.JTextField MPN;
    private javax.swing.JTextField NN;
    private javax.swing.JTextField NXB;
    private javax.swing.JTextField NamXB;
    private javax.swing.JTextField SL;
    private javax.swing.JTextField TG;
    private javax.swing.JTextField TL;
    private javax.swing.JTextField TS;
    private javax.swing.JLabel TSF;
    private javax.swing.JButton ThemSach;
    private javax.swing.JButton TraCuuPN;
    private javax.swing.JButton XoaSach;
    private com.component.Background background1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_nxb;
    private javax.swing.JLabel lb_maphieu;
    private javax.swing.JLabel lb_ngaynhap;
    private javax.swing.JLabel lb_soluong;
    private javax.swing.JLabel lb_tacgia;
    private javax.swing.JLabel lb_tensach;
    private javax.swing.JLabel lb_theloai;
    private javax.swing.JLabel lb_theloai1;
    private com.swing.PanelBorder tablePanel;
    private javax.swing.JTable tb_phieunhap;
    private javax.swing.JLabel title_PN;
    // End of variables declaration//GEN-END:variables
}
