/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static UI.DatabaseConnect.getJDBCConnection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ACER
 */
public class QLTL extends javax.swing.JPanel {
    Connection conn = getJDBCConnection();
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form TraCuu
     */
    public QLTL() {
        initComponents();
        setTable1Header();
        loadTable1();
    }
    private void loadTable1(){
      // create jTable1 columns
      DefaultTableModel model = new DefaultTableModel(){
          //không cho chỉnh sửa trong bảng
          @Override
      public boolean isCellEditable(int row, int column) {
          return false;
      }
      };

      String tieude[] = new String[]{"Mã thể loại", "Tên thể loại"};
      model.setColumnIdentifiers(tieude);
      String sql = "SELECT * FROM theloai";
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("MATHELOAI"),rs.getString("TENTHELOAI")});
            }
            tb_phieunhap.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(QLTL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setTable1Header(){
        tb_phieunhap.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            l.setBackground(new Color(0,88,128));
            l.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
            l.setHorizontalAlignment(CENTER);
            l.setFont(new Font("Segoe UI",Font.BOLD, 16));            
            return l;
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        Sua = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_phieunhap = new javax.swing.JTable();
        tx_tentheloai = new javax.swing.JTextField();
        lb_masach5 = new javax.swing.JLabel();
        Xoa = new rojerusan.RSMaterialButtonRectangle();
        Them = new rojerusan.RSMaterialButtonRectangle();

        kGradientPanel1.setBackground(new java.awt.Color(205, 241, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 171, 253));
        kGradientPanel1.setkStartColor(new java.awt.Color(205, 241, 255));

        rSMaterialButtonRectangle2.setText("QUẢN LÝ THỂ LOẠI");
        rSMaterialButtonRectangle2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N

        Sua.setText("SỬA");
        Sua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sua.setSelected(true);
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        tb_phieunhap.setBackground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setForeground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã thể loại", "Tên thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_phieunhap.setFillsViewportHeight(true);
        tb_phieunhap.setGridColor(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setRowHeight(40);
        tb_phieunhap.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setSelectionForeground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_phieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_phieunhap);

        lb_masach5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_masach5.setText("Tên thể loại");

        Xoa.setText("XÓA");
        Xoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Xoa.setSelected(true);
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Them.setText("THÊM");
        Them.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Them.setSelected(true);
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lb_masach5)
                        .addGap(18, 18, 18)
                        .addComponent(tx_tentheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_tentheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_masach5))
                .addGap(19, 19, 19)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        String tentheloai = tx_tentheloai.getText();
        int selectedRow = tb_phieunhap.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(QLTL.this, "Vui lòng chọn một dòng");
            return;
        }
        if(tentheloai.isBlank()){
            JOptionPane.showMessageDialog(QLTL.this, "Vui lòng nhập tên thể loại");
            return;
        }
        String sql = "UPDATE THELOAI SET TENTHELOAI = ? WHERE MATHELOAI = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, tentheloai);
            ps.setString(2, tb_phieunhap.getValueAt(selectedRow, 0).toString());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(QLTL.this, "Cập nhật thể loại thành công");
            loadTable1();
            tx_tentheloai.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(QLTL.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SuaActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        int selectedRow = tb_phieunhap.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(QLTL.this, "Vui lòng chọn một dòng");
            return;
        }
        String sql = "DELETE FROM THELOAI WHERE MATHELOAI = ?";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, tb_phieunhap.getValueAt(selectedRow, 0).toString());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(QLTL.this, "Xóa thể loại thành công");
            loadTable1();
            tx_tentheloai.setText("");
        } catch (SQLException ex) {
            if(ex.getMessage().contains("Cannot delete")){
                JOptionPane.showMessageDialog(QLTL.this, "Không thể xóa do vẫn còn dữ liệu liên quan");
            }
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        String tentheloai = tx_tentheloai.getText();
        if(tentheloai.isBlank()){
            JOptionPane.showMessageDialog(QLTL.this, "Vui lòng nhập tên thể loại");
            return;
        }
        String sql = "INSERT INTO THELOAI (TENTHELOAI) VALUES (?)";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, tentheloai);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(QLTL.this, "Thêm thể loại thành công");
            loadTable1();
            tx_tentheloai.setText("");
        } catch (SQLException ex) {
            if(ex.getMessage().contains("Duplicate entry")){
                JOptionPane.showMessageDialog(QLTL.this, "Tên thể loại đã tồn tại");
            }
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void tb_phieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_phieunhapMouseClicked
        int rowNo = tb_phieunhap.getSelectedRow();
        if(rowNo < 0 ) return;
        tx_tentheloai.setText(tb_phieunhap.getValueAt(rowNo, 1).toString());
    }//GEN-LAST:event_tb_phieunhapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Sua;
    private rojerusan.RSMaterialButtonRectangle Them;
    private rojerusan.RSMaterialButtonRectangle Xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lb_masach5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JTable tb_phieunhap;
    private javax.swing.JTextField tx_tentheloai;
    // End of variables declaration//GEN-END:variables
}
