/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JFrame;

/**
 *
 * @author DELL5289
 */
public class TracuuPhieunhap extends javax.swing.JPanel {

    /**
     * Creates new form TracuuPhieunhap
     */
    public TracuuPhieunhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_phieunhap = new javax.swing.JTable();
        title_PN = new javax.swing.JLabel();
        lb_ngaynhap = new javax.swing.JLabel();
        tx_ngaynhap = new javax.swing.JTextField();
        tx_maphieu = new javax.swing.JTextField();
        lb_maphieu = new javax.swing.JLabel();
        bt_tracuu = new javax.swing.JButton();
        bt_chinhsua = new javax.swing.JButton();
        background1 = new com.component.Background();

        setPreferredSize(new java.awt.Dimension(838, 651));

        tb_phieunhap.setBackground(new java.awt.Color(0, 88, 128));
        tb_phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu", "Ngày nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_phieunhap.setGridColor(new java.awt.Color(255, 255, 255));
        tb_phieunhap.setRowHeight(40);
        tb_phieunhap.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jScrollPane1.setViewportView(tb_phieunhap);

        title_PN.setBackground(new java.awt.Color(0, 0, 153));
        title_PN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        title_PN.setForeground(new java.awt.Color(0, 0, 102));
        title_PN.setText("PHIẾU NHẬP SÁCH");
        title_PN.setInheritsPopupMenu(false);

        lb_ngaynhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ngaynhap.setText("Ngày nhập");

        lb_maphieu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lb_maphieu.setText("Mã phiếu");

        bt_tracuu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bt_tracuu.setText("Tra cứu");
        bt_tracuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tracuuMouseClicked(evt);
            }
        });

        bt_chinhsua.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bt_chinhsua.setText("Chỉnh sửa");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_maphieu)
                        .addGap(18, 18, 18)
                        .addComponent(tx_maphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_ngaynhap)
                                .addGap(18, 18, 18)
                                .addComponent(tx_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_chinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(547, 547, 547)
                                .addComponent(bt_tracuu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(title_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(title_PN)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ngaynhap)
                    .addComponent(tx_maphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_maphieu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_chinhsua)
                    .addComponent(bt_tracuu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bt_chinhsua.getAccessibleContext().setAccessibleName("bt_chinhsua");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_tracuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tracuuMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        ChitietPhieunhap chitiet = new ChitietPhieunhap();
        frame.add(chitiet);
        frame.setSize(838, 651);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_bt_tracuuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.component.Background background1;
    private javax.swing.JButton bt_chinhsua;
    private javax.swing.JButton bt_tracuu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_maphieu;
    private javax.swing.JLabel lb_ngaynhap;
    private javax.swing.JTable tb_phieunhap;
    private javax.swing.JLabel title_PN;
    private javax.swing.JTextField tx_maphieu;
    private javax.swing.JTextField tx_ngaynhap;
    // End of variables declaration//GEN-END:variables
}
